import json
import os

class Localization:
    def __init__(self, default_lang='id'):
        self.current_lang = default_lang
        self.translations = {}
        self.load_translations()

    def load_translations(self):
        """Load translation files"""
        lang_dir = os.path.join(os.path.dirname(__file__), 'lang')

        # Default Indonesian translations
        self.translations['id'] = {
            'app_title': 'MyAnimeList & Nekopoi Scraper GUI',
            'year_label': 'Tahun:',
            'season_label': 'Musim:',
            'member_threshold_label': 'Ambang Batas Anggota:',
            'output_format_label': 'Format Output:',
            'start_scraping': 'Mulai Scraping',
            'save_results': 'Simpan Hasil',
            'filter_search': 'Filter & Cari',
            'progress_title': 'Progress',
            'results_title': 'Preview Hasil',
            'ready_status': 'Siap untuk scraping...',
            'scraping_mal': 'Scraping MyAnimeList...',
            'scraping_nekopoi': 'Scraping Nekopoi...',
            'scraping_completed': 'Scraping selesai!',
            'error_title': 'Error',
            'success_title': 'Berhasil',
            'warning_title': 'Peringatan',
            'no_data_warning': 'Tidak ada data untuk disimpan. Silakan scrape terlebih dahulu.',
            'save_success': 'Hasil disimpan ke: {path}',
            'scraping_failed': 'Scraping gagal: {error}',
            'invalid_year': 'Masukkan tahun yang valid (1917 atau lebih baru)',
            'invalid_threshold': 'Masukkan ambang batas anggota yang valid',
            'filter_window_title': 'Filter & Cari',
            'search_title_label': 'Cari Judul:',
            'min_members_label': 'Min Anggota:',
            'genre_label': 'Genre:',
            'studio_label': 'Studio:',
            'apply_filter': 'Terapkan Filter',
            'mal_data': 'Data MyAnimeList',
            'nekopoi_data': 'Data Nekopoi',
            'filtered_results': 'Hasil Filter: {mal} MAL, {nekopoi} Nekopoi',
            'seasons': ['winter', 'spring', 'summer', 'fall'],
            'season_names': ['Musim Dingin', 'Semi', 'Panas', 'Gugur'],
            'formats': ['txt', 'json', 'csv', 'pdf'],
            'format_names': ['Teks (TXT)', 'JSON', 'CSV', 'PDF'],
            'scrape_options_label': 'Opsi Scraping:',
            'no_source_selected': 'Silakan pilih setidaknya satu sumber data untuk di-scrape',
            'mal_scrape_failed': 'Scraping MyAnimeList gagal atau tidak mengembalikan data',
            'nekopoi_scrape_failed': 'Scraping Nekopoi gagal atau tidak mengembalikan data',
            'data_usage_label': 'Penggunaan Data:'
        }

        # English translations
        self.translations['en'] = {
            'app_title': 'MyAnimeList & Nekopoi Scraper GUI',
            'year_label': 'Year:',
            'season_label': 'Season:',
            'member_threshold_label': 'Member Threshold:',
            'output_format_label': 'Output Format:',
            'start_scraping': 'Start Scraping',
            'save_results': 'Save Results',
            'filter_search': 'Filter & Search',
            'progress_title': 'Progress',
            'results_title': 'Results Preview',
            'ready_status': 'Ready to scrape...',
            'scraping_mal': 'Scraping MyAnimeList...',
            'scraping_nekopoi': 'Scraping Nekopoi...',
            'scraping_completed': 'Scraping completed!',
            'error_title': 'Error',
            'success_title': 'Success',
            'warning_title': 'Warning',
            'no_data_warning': 'No data to save. Please scrape first.',
            'save_success': 'Results saved to: {path}',
            'scraping_failed': 'Scraping failed: {error}',
            'invalid_year': 'Please enter a valid year (1917 or later)',
            'invalid_threshold': 'Please enter a valid member threshold',
            'filter_window_title': 'Filter & Search',
            'search_title_label': 'Search Title:',
            'min_members_label': 'Min Members:',
            'genre_label': 'Genre:',
            'studio_label': 'Studio:',
            'apply_filter': 'Apply Filter',
            'mal_data': 'MyAnimeList Data',
            'nekopoi_data': 'Nekopoi Data',
            'filtered_results': 'Filtered Results: {mal} MAL, {nekopoi} Nekopoi',
            'seasons': ['winter', 'spring', 'summer', 'fall'],
            'season_names': ['Winter', 'Spring', 'Summer', 'Fall'],
            'formats': ['txt', 'json', 'csv', 'pdf'],
            'format_names': ['Text (TXT)', 'JSON', 'CSV', 'PDF'],
            'scrape_options_label': 'Scrape Options:',
            'no_source_selected': 'Please select at least one data source to scrape',
            'mal_scrape_failed': 'MyAnimeList scraping failed or returned no data',
            'nekopoi_scrape_failed': 'Nekopoi scraping failed or returned no data',
            'data_usage_label': 'Data Usage:'
        }

        # Japanese translations
        self.translations['ja'] = {
            'app_title': 'MyAnimeList & Nekopoi Scraper GUI',
            'year_label': '年:',
            'season_label': '季節:',
            'member_threshold_label': 'メンバーしきい値:',
            'output_format_label': '出力形式:',
            'start_scraping': 'スクレイピング開始',
            'save_results': '結果を保存',
            'filter_search': 'フィルター & 検索',
            'progress_title': '進捗',
            'results_title': '結果プレビュー',
            'ready_status': 'スクレイピングの準備完了...',
            'scraping_mal': 'MyAnimeListをスクレイピング中...',
            'scraping_nekopoi': 'Nekopoiをスクレイピング中...',
            'scraping_completed': 'スクレイピング完了！',
            'error_title': 'エラー',
            'success_title': '成功',
            'warning_title': '警告',
            'no_data_warning': '保存するデータがありません。まずスクレイピングしてください。',
            'save_success': '結果を保存しました: {path}',
            'scraping_failed': 'スクレイピング失敗: {error}',
            'invalid_year': '有効な年を入力してください（1917年以降）',
            'invalid_threshold': '有効なメンバーのしきい値を入力してください',
            'filter_window_title': 'フィルター & 検索',
            'search_title_label': 'タイトル検索:',
            'min_members_label': '最小メンバー数:',
            'genre_label': 'ジャンル:',
            'studio_label': 'スタジオ:',
            'apply_filter': 'フィルター適用',
            'mal_data': 'MyAnimeListデータ',
            'nekopoi_data': 'Nekopoiデータ',
            'filtered_results': 'フィルター結果: {mal} MAL, {nekopoi} Nekopoi',
            'seasons': ['winter', 'spring', 'summer', 'fall'],
            'season_names': ['冬', '春', '夏', '秋'],
            'formats': ['txt', 'json', 'csv', 'pdf'],
            'format_names': ['テキスト (TXT)', 'JSON', 'CSV', 'PDF'],
            'scrape_options_label': 'スクレイプオプション:',
            'no_source_selected': '少なくとも1つのデータソースを選択してください',
            'mal_scrape_failed': 'MyAnimeListスクレイピングが失敗したかデータを返しませんでした',
            'nekopoi_scrape_failed': 'Nekopoiスクレイピングが失敗したかデータを返しませんでした',
            'data_usage_label': 'データ使用量:'
        }

        # Spanish translations
        self.translations['es'] = {
            'app_title': 'MyAnimeList & Nekopoi Scraper GUI',
            'year_label': 'Año:',
            'season_label': 'Temporada:',
            'member_threshold_label': 'Umbral de Miembros:',
            'output_format_label': 'Formato de Salida:',
            'start_scraping': 'Iniciar Scraping',
            'save_results': 'Guardar Resultados',
            'filter_search': 'Filtrar & Buscar',
            'progress_title': 'Progreso',
            'results_title': 'Vista Previa de Resultados',
            'ready_status': 'Listo para scrapear...',
            'scraping_mal': 'Scrapeando MyAnimeList...',
            'scraping_nekopoi': 'Scrapeando Nekopoi...',
            'scraping_completed': '¡Scraping completado!',
            'error_title': 'Error',
            'success_title': 'Éxito',
            'warning_title': 'Advertencia',
            'no_data_warning': 'No hay datos para guardar. Por favor, scrape primero.',
            'save_success': 'Resultados guardados en: {path}',
            'scraping_failed': 'Scraping falló: {error}',
            'invalid_year': 'Por favor ingrese un año válido (1917 o posterior)',
            'invalid_threshold': 'Por favor ingrese un umbral de miembros válido',
            'filter_window_title': 'Filtrar & Buscar',
            'search_title_label': 'Buscar Título:',
            'min_members_label': 'Mín. Miembros:',
            'genre_label': 'Género:',
            'studio_label': 'Estudio:',
            'apply_filter': 'Aplicar Filtro',
            'mal_data': 'Datos de MyAnimeList',
            'nekopoi_data': 'Datos de Nekopoi',
            'filtered_results': 'Resultados Filtrados: {mal} MAL, {nekopoi} Nekopoi',
            'scrape_options_label': 'Opciones de Scraping:',
            'no_source_selected': 'Por favor seleccione al menos una fuente de datos para scrapear',
            'mal_scrape_failed': 'El scraping de MyAnimeList falló o no devolvió datos',
            'nekopoi_scrape_failed': 'El scraping de Nekopoi falló o no devolvió datos',
            'data_usage_label': 'Uso de Datos:',
            'seasons': ['winter', 'spring', 'summer', 'fall'],
            'season_names': ['Invierno', 'Primavera', 'Verano', 'Otoño'],
            'formats': ['txt', 'json', 'csv', 'pdf'],
            'format_names': ['Texto (TXT)', 'JSON', 'CSV', 'PDF']
        }

        # Chinese (Simplified) translations
        self.translations['zh'] = {
            'app_title': 'MyAnimeList & Nekopoi 刮取器 GUI',
            'year_label': '年份:',
            'season_label': '季节:',
            'member_threshold_label': '成员阈值:',
            'output_format_label': '输出格式:',
            'start_scraping': '开始刮取',
            'save_results': '保存结果',
            'filter_search': '筛选 & 搜索',
            'progress_title': '进度',
            'results_title': '结果预览',
            'ready_status': '准备刮取...',
            'scraping_mal': '正在刮取 MyAnimeList...',
            'scraping_nekopoi': '正在刮取 Nekopoi...',
            'scraping_completed': '刮取完成！',
            'error_title': '错误',
            'success_title': '成功',
            'warning_title': '警告',
            'no_data_warning': '没有数据可保存。请先刮取。',
            'save_success': '结果已保存到: {path}',
            'scraping_failed': '刮取失败: {error}',
            'invalid_year': '请输入有效年份（1917年或之后）',
            'invalid_threshold': '请输入有效的成员阈值',
            'filter_window_title': '筛选 & 搜索',
            'search_title_label': '搜索标题:',
            'min_members_label': '最小成员数:',
            'genre_label': '类型:',
            'studio_label': '工作室:',
            'apply_filter': '应用筛选',
            'mal_data': 'MyAnimeList 数据',
            'nekopoi_data': 'Nekopoi 数据',
            'filtered_results': '筛选结果: {mal} MAL, {nekopoi} Nekopoi',
            'seasons': ['winter', 'spring', 'summer', 'fall'],
            'season_names': ['冬季', '春季', '夏季', '秋季'],
            'formats': ['txt', 'json', 'csv', 'pdf'],
            'format_names': ['文本 (TXT)', 'JSON', 'CSV', 'PDF'],
            'scrape_options_label': '刮取选项:',
            'no_source_selected': '请至少选择一个数据源进行刮取',
            'mal_scrape_failed': 'MyAnimeList 刮取失败或未返回数据',
            'nekopoi_scrape_failed': 'Nekopoi 刮取失败或未返回数据',
            'data_usage_label': '数据使用量:'
        }

        # Korean translations
        self.translations['ko'] = {
            'app_title': 'MyAnimeList & Nekopoi 스크래퍼 GUI',
            'year_label': '년:',
            'season_label': '계절:',
            'member_threshold_label': '회원 임계값:',
            'output_format_label': '출력 형식:',
            'start_scraping': '스크래핑 시작',
            'save_results': '결과 저장',
            'filter_search': '필터 & 검색',
            'progress_title': '진행',
            'results_title': '결과 미리보기',
            'ready_status': '스크래핑 준비 완료...',
            'scraping_mal': 'MyAnimeList 스크래핑 중...',
            'scraping_nekopoi': 'Nekopoi 스크래핑 중...',
            'scraping_completed': '스크래핑 완료!',
            'error_title': '오류',
            'success_title': '성공',
            'warning_title': '경고',
            'no_data_warning': '저장할 데이터가 없습니다. 먼저 스크래핑하세요.',
            'save_success': '결과가 다음 위치에 저장됨: {path}',
            'scraping_failed': '스크래핑 실패: {error}',
            'invalid_year': '유효한 년도를 입력하세요 (1917년 이후)',
            'invalid_threshold': '유효한 회원 임계값을 입력하세요',
            'filter_window_title': '필터 & 검색',
            'search_title_label': '제목 검색:',
            'min_members_label': '최소 회원 수:',
            'genre_label': '장르:',
            'studio_label': '스튜디오:',
            'apply_filter': '필터 적용',
            'mal_data': 'MyAnimeList 데이터',
            'nekopoi_data': 'Nekopoi 데이터',
            'filtered_results': '필터링된 결과: {mal} MAL, {nekopoi} Nekopoi',
            'seasons': ['winter', 'spring', 'summer', 'fall'],
            'season_names': ['겨울', '봄', '여름', '가을'],
            'formats': ['txt', 'json', 'csv', 'pdf'],
            'format_names': ['텍스트 (TXT)', 'JSON', 'CSV', 'PDF'],
            'scrape_options_label': '스크래핑 옵션:',
            'no_source_selected': '스크래핑할 데이터 소스를 하나 이상 선택하세요',
            'mal_scrape_failed': 'MyAnimeList 스크래핑이 실패했거나 데이터를 반환하지 않았습니다',
            'nekopoi_scrape_failed': 'Nekopoi 스크래핑이 실패했거나 데이터를 반환하지 않았습니다',
            'data_usage_label': '데이터 사용량:'
        }

        # French translations
        self.translations['fr'] = {
            'app_title': 'MyAnimeList & Nekopoi Scraper GUI',
            'year_label': 'Année:',
            'season_label': 'Saison:',
            'member_threshold_label': 'Seuil de Membres:',
            'output_format_label': 'Format de Sortie:',
            'start_scraping': 'Démarrer le Scraping',
            'save_results': 'Sauvegarder les Résultats',
            'filter_search': 'Filtrer & Rechercher',
            'progress_title': 'Progrès',
            'results_title': 'Aperçu des Résultats',
            'ready_status': 'Prêt à scraper...',
            'scraping_mal': 'Scraping MyAnimeList...',
            'scraping_nekopoi': 'Scraping Nekopoi...',
            'scraping_completed': 'Scraping terminé!',
            'error_title': 'Erreur',
            'success_title': 'Succès',
            'warning_title': 'Avertissement',
            'no_data_warning': 'Aucune donnée à sauvegarder. Veuillez d\'abord scraper.',
            'save_success': 'Résultats sauvegardés dans: {path}',
            'scraping_failed': 'Échec du scraping: {error}',
            'invalid_year': 'Veuillez saisir une année valide (1917 ou ultérieure)',
            'invalid_threshold': 'Veuillez saisir un seuil de membres valide',
            'filter_window_title': 'Filtrer & Rechercher',
            'search_title_label': 'Rechercher Titre:',
            'min_members_label': 'Min. Membres:',
            'genre_label': 'Genre:',
            'studio_label': 'Studio:',
            'apply_filter': 'Appliquer le Filtre',
            'mal_data': 'Données MyAnimeList',
            'nekopoi_data': 'Données Nekopoi',
            'filtered_results': 'Résultats Filtrés: {mal} MAL, {nekopoi} Nekopoi',
            'seasons': ['winter', 'spring', 'summer', 'fall'],
            'season_names': ['Hiver', 'Printemps', 'Été', 'Automne'],
            'formats': ['txt', 'json', 'csv', 'pdf'],
            'format_names': ['Texte (TXT)', 'JSON', 'CSV', 'PDF'],
            'scrape_options_label': 'Options de Scraping:',
            'no_source_selected': 'Veuillez sélectionner au moins une source de données à scraper',
            'mal_scrape_failed': 'Le scraping MyAnimeList a échoué ou n\'a pas retourné de données',
            'nekopoi_scrape_failed': 'Le scraping Nekopoi a échoué ou n\'a pas retourné de données',
            'data_usage_label': 'Utilisation des Données:'
        }

        # German translations
        self.translations['de'] = {
            'app_title': 'MyAnimeList & Nekopoi Scraper GUI',
            'year_label': 'Jahr:',
            'season_label': 'Jahreszeit:',
            'member_threshold_label': 'Mitglieder-Schwellenwert:',
            'output_format_label': 'Ausgabeformat:',
            'start_scraping': 'Scraping Starten',
            'save_results': 'Ergebnisse Speichern',
            'filter_search': 'Filtern & Suchen',
            'progress_title': 'Fortschritt',
            'results_title': 'Ergebnisvorschau',
            'ready_status': 'Bereit zum Scrapen...',
            'scraping_mal': 'MyAnimeList wird gescrapt...',
            'scraping_nekopoi': 'Nekopoi wird gescrapt...',
            'scraping_completed': 'Scraping abgeschlossen!',
            'error_title': 'Fehler',
            'success_title': 'Erfolg',
            'warning_title': 'Warnung',
            'no_data_warning': 'Keine Daten zum Speichern. Bitte zuerst scrapen.',
            'save_success': 'Ergebnisse gespeichert in: {path}',
            'scraping_failed': 'Scraping fehlgeschlagen: {error}',
            'invalid_year': 'Bitte geben Sie ein gültiges Jahr ein (1917 oder später)',
            'invalid_threshold': 'Bitte geben Sie einen gültigen Mitglieder-Schwellenwert ein',
            'filter_window_title': 'Filtern & Suchen',
            'search_title_label': 'Titel suchen:',
            'min_members_label': 'Min. Mitglieder:',
            'genre_label': 'Genre:',
            'studio_label': 'Studio:',
            'apply_filter': 'Filter anwenden',
            'mal_data': 'MyAnimeList Daten',
            'nekopoi_data': 'Nekopoi Daten',
            'filtered_results': 'Gefilterte Ergebnisse: {mal} MAL, {nekopoi} Nekopoi',
            'seasons': ['winter', 'spring', 'summer', 'fall'],
            'season_names': ['Winter', 'Frühling', 'Sommer', 'Herbst'],
            'formats': ['txt', 'json', 'csv', 'pdf'],
            'format_names': ['Text (TXT)', 'JSON', 'CSV', 'PDF'],
            'scrape_options_label': 'Scraping-Optionen:',
            'no_source_selected': 'Bitte wählen Sie mindestens eine Datenquelle zum Scrapen aus',
            'mal_scrape_failed': 'MyAnimeList-Scraping ist fehlgeschlagen oder hat keine Daten zurückgegeben',
            'nekopoi_scrape_failed': 'Nekopoi-Scraping ist fehlgeschlagen oder hat keine Daten zurückgegeben',
            'data_usage_label': 'Datenverbrauch:'
        }

        # Portuguese translations
        self.translations['pt'] = {
            'app_title': 'MyAnimeList & Nekopoi Scraper GUI',
            'year_label': 'Ano:',
            'season_label': 'Temporada:',
            'member_threshold_label': 'Limite de Membros:',
            'output_format_label': 'Formato de Saída:',
            'start_scraping': 'Iniciar Scraping',
            'save_results': 'Salvar Resultados',
            'filter_search': 'Filtrar & Buscar',
            'progress_title': 'Progresso',
            'results_title': 'Pré-visualização de Resultados',
            'ready_status': 'Pronto para scrapear...',
            'scraping_mal': 'Scrapeando MyAnimeList...',
            'scraping_nekopoi': 'Scrapeando Nekopoi...',
            'scraping_completed': 'Scraping concluído!',
            'error_title': 'Erro',
            'success_title': 'Sucesso',
            'warning_title': 'Aviso',
            'no_data_warning': 'Nenhum dado para salvar. Por favor, scrape primeiro.',
            'save_success': 'Resultados salvos em: {path}',
            'scraping_failed': 'Scraping falhou: {error}',
            'invalid_year': 'Por favor insira um ano válido (1917 ou posterior)',
            'invalid_threshold': 'Por favor insira um limite de membros válido',
            'filter_window_title': 'Filtrar & Buscar',
            'search_title_label': 'Buscar Título:',
            'min_members_label': 'Mín. Membros:',
            'genre_label': 'Gênero:',
            'studio_label': 'Estúdio:',
            'apply_filter': 'Aplicar Filtro',
            'mal_data': 'Dados do MyAnimeList',
            'nekopoi_data': 'Dados do Nekopoi',
            'filtered_results': 'Resultados Filtrados: {mal} MAL, {nekopoi} Nekopoi',
            'seasons': ['winter', 'spring', 'summer', 'fall'],
            'season_names': ['Inverno', 'Primavera', 'Verão', 'Outono'],
            'formats': ['txt', 'json', 'csv', 'pdf'],
            'format_names': ['Texto (TXT)', 'JSON', 'CSV', 'PDF'],
            'scrape_options_label': 'Opções de Scraping:',
            'no_source_selected': 'Por favor selecione pelo menos uma fonte de dados para scrapear',
            'mal_scrape_failed': 'O scraping do MyAnimeList falhou ou não retornou dados',
            'nekopoi_scrape_failed': 'O scraping do Nekopoi falhou ou não retornou dados',
            'data_usage_label': 'Uso de Dados:'
        }

    def set_language(self, lang):
        """Set current language"""
        if lang in self.translations:
            self.current_lang = lang
            return True
        return False

    def get(self, key, **kwargs):
        """Get translated text"""
        if self.current_lang in self.translations and key in self.translations[self.current_lang]:
            text = self.translations[self.current_lang][key]
            if kwargs:
                text = text.format(**kwargs)
            return text
        return key  # Return key if translation not found

    def get_available_languages(self):
        """Get list of available languages"""
        return list(self.translations.keys())

    def get_language_name(self, lang_code):
        """Get human-readable language name"""
        names = {
            'id': 'Bahasa Indonesia',
            'en': 'English',
            'ja': '日本語 (Japanese)',
            'es': 'Español (Spanish)',
            'zh': '中文 (Chinese)',
            'ko': '한국어 (Korean)',
            'fr': 'Français (French)',
            'de': 'Deutsch (German)',
            'pt': 'Português (Portuguese)'
        }
        return names.get(lang_code, lang_code)

# Global instance
i18n = Localization()