name: 🐞 Bug Report
description: Report a bug or issue in the codebase
labels: [Bug, Needs Investigation]
assignees: [TheKingTermux]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the bug.
      placeholder: |
        Example:
          Clicking "Save" causes the app to freeze indefinitely.
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step guide to reproduce the issue.
      placeholder: |
        1. Go to 'Settings'
        2. Click on 'Save'
        3. Observe the app freezing
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: |
        Example:
          The app should save settings without freezing.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Mention your environment details (OS, version, browser, etc.)
      placeholder: |
        Example:
          - OS: Windows 11
          - Browser: Chrome 119
          - Version: 2.4.1

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs or Screenshots
      description: Attach logs or screenshots that help identify the issue.
